version: '3.8'

services:
  backend:
    image: aubay-api2
    container_name: backend
    ports:
      - "8000:8000"
      - "3306:3306"
    networks:
      - app-network

  frontend:
    image: aubay-apps
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  job:
    image: aubays-jobs
    container_name: job
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
